name: Lint Terraform

on:
  workflow_call:

jobs:
  lint-terraform:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Terraform fmt
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: fmt -check -recursive -diff

      - name: Terraform init
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: init

      - name: Terraform validate
        uses: docker://hashicorp/terraform:light
        with:
          entrypoint: terraform
          args: validate
